services:
  cta_front:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://cta_backend:8000/api/v1
    ports:
      - "3000:80"
    depends_on:
      - cta_backend
